customhost = "database-1.cek64lku9ctq.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "mypassword"
customdb = "employee"
custombucket = "bucket-for-project-sunilbennur"
customregion = "us-east-1"
